### ISSUE TITLE
Section 4.2 BP year clarification

### ISSUE THREAD

**Issue by marlenebellman** [FRAMverse/fram_doc#1]
In section 4.2 FRAM Base Period, the following text is incorrect for coho.  
"The current base period uses brood year releases from 2005-2008 for Chinook and 1982-1989 for coho. "

Please update the text to clarify,  
"The current Chinook base period uses CWT releases from brood years 2005-2008.  The coho base period is comprised of CWT recoveries from catch years 1986-1992."

Thanks, Marlene

**Comment by jshrov** [comment]
Thank you Marlene, it is now corrected in the text.
