### ISSUE TITLE
Appendix 1, 2, 3, 4

### ISSUE THREAD

**Issue by marlenebellman** [FRAMverse/fram_doc#2]
The assumption was that the Appendices for FRAM stocks and fisheries would contain the full table of reference information needed for stocks/fisheries, by taking the content of tables as in the prior version of the User Manual , Chapter 15.1 and 15.2 for Chinook and Chapter 16.1 and 16.2 for coho.  

Can you just copy and paste over the content from the User Manual site as it was?  

The current versions I see are not useful as an actual reference.....
Thanks, Marlene

**Comment by jshrov** [comment]
Thanks Marlene, the User Manual tables have now been carried over
