### ISSUE TITLE
Headings edit for Model Structure

### ISSUE THREAD

**Issue by marlenebellman** [FRAMverse/fram_doc#3]
Under Model Detail - the user can select Chinook or Coho.  Once that is selected, the menu at the left is visible, but once you have scrolled or clicked to another section, it is hard to remember if one is looking at the Chinook or Coho content. Currently the species differentiation is listed in another line that does not "show" in the menu. 

Therefore, is it possible to edit to the Heading text to read 
"1. Chinook Model Structure" and 
"1. Coho Model Structure"
so that it is referenced in the users view even when deeply navigating within each?

Thanks, Marlene

**Comment by jshrov** [comment]
Thanks Marlene, the headings on these two pages are now adjusted.
